#define HAVE_DLFCN_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SOCKET 1
#define HAVE_STAT_EMPTY_STRING_BUG 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCHR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRTOUL 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define PACKAGE "canutils"
#define PACKAGE_BUGREPORT "bugs@pengutronix.de"
#define PACKAGE_NAME "canutils"
#define PACKAGE_STRING "canutils 4.0.6"
#define PACKAGE_TARNAME "canutils"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "4.0.6"
#define RETSIGTYPE void
#define STDC_HEADERS 1
#define VERSION "4.0.6"
